name: SauceDemo Automation CI
on:
  push:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore

      - name: Show runner filesystem
        run: ls -R

      - name: Find TestResults folder
        run: find . -type d -name "TestResults"

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Show bin folder
        if: always()
        run: ls -R bin

      - name: Show TestResults after TestRun
        if: always()
        run: ls -R TestResults || echo "TestResults not found"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test-Results
          path: "**/TestResults/**"
s